
#include <odbcinst.h>
#include <sql.h>
#include <sqlext.h>

int _SQL_ATTR_ODBC_VERSION = SQL_ATTR_ODBC_VERSION;
int _SQL_ATTR_CONNECTION_POOLING = SQL_ATTR_CONNECTION_POOLING;
SQLPOINTER _SQL_CP_ONE_PER_DRIVER = (SQLPOINTER)SQL_CP_ONE_PER_DRIVER;
SQLPOINTER _SQL_OV_ODBC3_80 = (SQLPOINTER)SQL_OV_ODBC3_80;
SQLPOINTER _SQL_OV_ODBC3 = (SQLPOINTER)SQL_OV_ODBC3;
