
#include <odbcinst.h>
#include <sql.h>
#include <sqlext.h>

const int _SQL_ATTR_ODBC_VERSION = SQL_ATTR_ODBC_VERSION;
const int _SQL_ATTR_CONNECTION_POOLING = SQL_ATTR_CONNECTION_POOLING;
const SQLPOINTER _SQL_CP_ONE_PER_DRIVER = (SQLPOINTER)SQL_CP_ONE_PER_DRIVER;
const SQLPOINTER _SQL_OV_ODBC3_80 = (SQLPOINTER)SQL_OV_ODBC3_80;
const SQLPOINTER _SQL_OV_ODBC3 = (SQLPOINTER)SQL_OV_ODBC3;

const short
_SQL_CHAR = SQL_CHAR,
_SQL_VARCHAR = SQL_VARCHAR,
_SQL_LONGVARCHAR = SQL_LONGVARCHAR,
_SQL_WCHAR = SQL_WCHAR,
_SQL_WVARCHAR = SQL_WVARCHAR,
_SQL_WLONGVARCHAR = SQL_WLONGVARCHAR,
_SQL_DECIMAL = SQL_DECIMAL,
_SQL_NUMERIC = SQL_NUMERIC,
_SQL_SMALLINT = SQL_SMALLINT,
_SQL_INTEGER = SQL_INTEGER,
_SQL_REAL = SQL_REAL,
_SQL_FLOAT = SQL_FLOAT,
_SQL_DOUBLE = SQL_DOUBLE,
_SQL_BIT = SQL_BIT,
_SQL_TINYINT = SQL_TINYINT,
_SQL_BIGINT = SQL_BIGINT,
_SQL_BINARY = SQL_BINARY,
_SQL_VARBINARY = SQL_VARBINARY,
_SQL_LONGVARBINARY = SQL_LONGVARBINARY,
_SQL_TYPE_DATE = SQL_TYPE_DATE,
_SQL_TYPE_TIME = SQL_TYPE_TIME,
_SQL_TYPE_TIMESTAMP = SQL_TYPE_TIMESTAMP,
_SQL_INTERVAL_MONTH = SQL_INTERVAL_MONTH,
_SQL_INTERVAL_YEAR = SQL_INTERVAL_YEAR,
_SQL_INTERVAL_YEAR_TO_MONTH = SQL_INTERVAL_YEAR_TO_MONTH,
_SQL_INTERVAL_DAY = SQL_INTERVAL_DAY,
_SQL_INTERVAL_HOUR = SQL_INTERVAL_HOUR,
_SQL_INTERVAL_MINUTE = SQL_INTERVAL_MINUTE,
_SQL_INTERVAL_SECOND = SQL_INTERVAL_SECOND,
_SQL_INTERVAL_DAY_TO_HOUR = SQL_INTERVAL_DAY_TO_HOUR,
_SQL_INTERVAL_DAY_TO_MINUTE = SQL_INTERVAL_DAY_TO_MINUTE,
_SQL_INTERVAL_DAY_TO_SECOND = SQL_INTERVAL_DAY_TO_SECOND,
_SQL_INTERVAL_HOUR_TO_MINUTE = SQL_INTERVAL_HOUR_TO_MINUTE,
_SQL_INTERVAL_HOUR_TO_SECOND = SQL_INTERVAL_HOUR_TO_SECOND,
_SQL_INTERVAL_MINUTE_TO_SECOND = SQL_INTERVAL_MINUTE_TO_SECOND,
_SQL_GUID = SQL_GUID,
_SQL_C_DEFAULT = SQL_C_DEFAULT,
_SQL_C_SBIGINT = SQL_C_SBIGINT,
_SQL_C_UBIGINT = SQL_C_UBIGINT,
_SQL_C_SLONG = SQL_C_SLONG,
_SQL_C_ULONG = SQL_C_ULONG,
_SQL_C_SSHORT = SQL_C_SSHORT,
_SQL_C_USHORT = SQL_C_USHORT,
_SQL_C_STINYINT = SQL_C_STINYINT,
_SQL_C_UTINYINT = SQL_C_UTINYINT,
_SQL_UNKNOWN_TYPE = SQL_UNKNOWN_TYPE;
